// Copyright 2012 Metropolitan Transportation Authority
//
// Protocol definition NYCT-specific extensions to GTFS-realtime.
//
// As originally posted at:
//
//   https://groups.google.com/d/msg/gtfs-realtime/KWJhkXH0kBg/8rlRMxiL-ysJ

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/pb/gtfs_realtime_nyct.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The direction the train is moving.
type NyctTripDescriptor_Direction int32

const (
	NyctTripDescriptor_NORTH NyctTripDescriptor_Direction = 1
	NyctTripDescriptor_EAST  NyctTripDescriptor_Direction = 2
	NyctTripDescriptor_SOUTH NyctTripDescriptor_Direction = 3
	NyctTripDescriptor_WEST  NyctTripDescriptor_Direction = 4
)

// Enum value maps for NyctTripDescriptor_Direction.
var (
	NyctTripDescriptor_Direction_name = map[int32]string{
		1: "NORTH",
		2: "EAST",
		3: "SOUTH",
		4: "WEST",
	}
	NyctTripDescriptor_Direction_value = map[string]int32{
		"NORTH": 1,
		"EAST":  2,
		"SOUTH": 3,
		"WEST":  4,
	}
)

func (x NyctTripDescriptor_Direction) Enum() *NyctTripDescriptor_Direction {
	p := new(NyctTripDescriptor_Direction)
	*p = x
	return p
}

func (x NyctTripDescriptor_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NyctTripDescriptor_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_gtfs_realtime_nyct_proto_enumTypes[0].Descriptor()
}

func (NyctTripDescriptor_Direction) Type() protoreflect.EnumType {
	return &file_internal_pb_gtfs_realtime_nyct_proto_enumTypes[0]
}

func (x NyctTripDescriptor_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NyctTripDescriptor_Direction) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NyctTripDescriptor_Direction(num)
	return nil
}

// Deprecated: Use NyctTripDescriptor_Direction.Descriptor instead.
func (NyctTripDescriptor_Direction) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_gtfs_realtime_nyct_proto_rawDescGZIP(), []int{2, 0}
}

type TripReplacementPeriod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The replacement period is for this route
	RouteId *string `protobuf:"bytes,1,opt,name=route_id,json=routeId" json:"route_id,omitempty"`
	// The start time is omitted, the end time is currently now + 30 minutes for
	// all routes of the A division
	ReplacementPeriod *TimeRange `protobuf:"bytes,2,opt,name=replacement_period,json=replacementPeriod" json:"replacement_period,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TripReplacementPeriod) Reset() {
	*x = TripReplacementPeriod{}
	mi := &file_internal_pb_gtfs_realtime_nyct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripReplacementPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripReplacementPeriod) ProtoMessage() {}

func (x *TripReplacementPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_gtfs_realtime_nyct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripReplacementPeriod.ProtoReflect.Descriptor instead.
func (*TripReplacementPeriod) Descriptor() ([]byte, []int) {
	return file_internal_pb_gtfs_realtime_nyct_proto_rawDescGZIP(), []int{0}
}

func (x *TripReplacementPeriod) GetRouteId() string {
	if x != nil && x.RouteId != nil {
		return *x.RouteId
	}
	return ""
}

func (x *TripReplacementPeriod) GetReplacementPeriod() *TimeRange {
	if x != nil {
		return x.ReplacementPeriod
	}
	return nil
}

// NYCT Subway extensions for the feed header
type NyctFeedHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version of the NYCT Subway extensions
	// The current version is 1.0
	NyctSubwayVersion *string `protobuf:"bytes,1,req,name=nyct_subway_version,json=nyctSubwayVersion" json:"nyct_subway_version,omitempty"`
	// For the NYCT Subway, the GTFS-realtime feed replaces any scheduled
	// trip within the trip_replacement_period.
	// This feed is a full dataset, it contains all trips starting
	// in the trip_replacement_period. If a trip from the static GTFS is not
	// found in the GTFS-realtime feed, it should be considered as cancelled.
	// The replacement period can be different for each route, so here is
	// a list of the routes where the trips in the feed replace all
	// scheduled trips within the replacement period.
	TripReplacementPeriod []*TripReplacementPeriod `protobuf:"bytes,2,rep,name=trip_replacement_period,json=tripReplacementPeriod" json:"trip_replacement_period,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NyctFeedHeader) Reset() {
	*x = NyctFeedHeader{}
	mi := &file_internal_pb_gtfs_realtime_nyct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NyctFeedHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NyctFeedHeader) ProtoMessage() {}

func (x *NyctFeedHeader) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_gtfs_realtime_nyct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NyctFeedHeader.ProtoReflect.Descriptor instead.
func (*NyctFeedHeader) Descriptor() ([]byte, []int) {
	return file_internal_pb_gtfs_realtime_nyct_proto_rawDescGZIP(), []int{1}
}

func (x *NyctFeedHeader) GetNyctSubwayVersion() string {
	if x != nil && x.NyctSubwayVersion != nil {
		return *x.NyctSubwayVersion
	}
	return ""
}

func (x *NyctFeedHeader) GetTripReplacementPeriod() []*TripReplacementPeriod {
	if x != nil {
		return x.TripReplacementPeriod
	}
	return nil
}

// NYCT Subway extensions for the trip descriptor
type NyctTripDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The nyct_train_id is meant for internal use only. It provides an
	// easy way to associated GTFS-realtime trip identifiers with NYCT rail
	// operations identifier
	//
	// The ATS office system assigns unique train identification (Train ID) to
	// each train operating within or ready to enter the mainline of the
	// monitored territory. An example of this is 06 0123+ PEL/BBR and is decoded
	// as follows:
	//
	// The first character represents the trip type designator. 0 identifies a
	// scheduled revenue trip. Other revenue trip values that are a result of a
	// change to the base schedule include; [= reroute], [/ skip stop], [$ turn
	// train] also known as shortly lined service.
	//
	// The second character 6 represents the trip line i.e. number 6 train The
	// third set of characters identify the decoded origin time. The last
	// character may be blank "on the whole minute" or + "30 seconds"
	//
	// Note: Origin times will not change when there is a trip type change.  This
	// is followed by a three character "Origin Location" / "Destination
	// Location"
	TrainId *string `protobuf:"bytes,1,opt,name=train_id,json=trainId" json:"train_id,omitempty"`
	// This trip has been assigned to a physical train. If true, this trip is
	// already underway or most likely will depart shortly.
	//
	// Train Assignment is a function of the Automatic Train Supervision (ATS)
	// office system used by NYCT Rail Operations to monitor and track train
	// movements. ATS provides the ability to "assign" the nyct_train_id
	// attribute when a physical train is at its origin terminal. These assigned
	// trips have the is_assigned field set in the TripDescriptor.
	//
	// When a train is at a terminal but has not been given a work program it is
	// declared unassigned and is tagged as such. Unassigned trains can be moved
	// to a storage location or assigned a nyct_train_id when a determination for
	// service is made.
	IsAssigned *bool `protobuf:"varint,2,opt,name=is_assigned,json=isAssigned" json:"is_assigned,omitempty"`
	// Uptown and Bronx-bound trains are moving NORTH.
	// Times Square Shuttle to Grand Central is also northbound.
	//
	// Downtown and Brooklyn-bound trains are moving SOUTH.
	// Times Square Shuttle to Times Square is also southbound.
	//
	// EAST and WEST are not used currently.
	Direction     *NyctTripDescriptor_Direction `protobuf:"varint,3,opt,name=direction,enum=pb.NyctTripDescriptor_Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NyctTripDescriptor) Reset() {
	*x = NyctTripDescriptor{}
	mi := &file_internal_pb_gtfs_realtime_nyct_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NyctTripDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NyctTripDescriptor) ProtoMessage() {}

func (x *NyctTripDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_gtfs_realtime_nyct_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NyctTripDescriptor.ProtoReflect.Descriptor instead.
func (*NyctTripDescriptor) Descriptor() ([]byte, []int) {
	return file_internal_pb_gtfs_realtime_nyct_proto_rawDescGZIP(), []int{2}
}

func (x *NyctTripDescriptor) GetTrainId() string {
	if x != nil && x.TrainId != nil {
		return *x.TrainId
	}
	return ""
}

func (x *NyctTripDescriptor) GetIsAssigned() bool {
	if x != nil && x.IsAssigned != nil {
		return *x.IsAssigned
	}
	return false
}

func (x *NyctTripDescriptor) GetDirection() NyctTripDescriptor_Direction {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return NyctTripDescriptor_NORTH
}

// NYCT Subway extensions for the stop time update
type NyctStopTimeUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provides the planned station arrival track. The following is the Manhattan
	// track configurations:
	// 1: southbound local
	// 2: southbound express
	// 3: northbound express
	// 4: northbound local
	//
	// In the Bronx (except Dyre Ave line)
	// M: bi-directional express (in the AM express to Manhattan, in the PM
	// express away).
	//
	// The Dyre Ave line is configured:
	// 1: southbound
	// 2: northbound
	// 3: bi-directional
	ScheduledTrack *string `protobuf:"bytes,1,opt,name=scheduled_track,json=scheduledTrack" json:"scheduled_track,omitempty"`
	// This is the actual track that the train is operating on and can be used to
	// determine if a train is operating according to its current schedule
	// (plan).
	//
	// The actual track is known only shortly before the train reaches a station,
	// typically not before it leaves the previous station. Therefore, the NYCT
	// feed sets this field only for the first station of the remaining trip.
	//
	// Different actual and scheduled track is the result of manually rerouting a
	// train off it scheduled path.  When this occurs, prediction data may become
	// unreliable since the train is no longer operating in accordance to its
	// schedule.  The rules engine for the 'countdown' clocks will remove this
	// train from all schedule stations.
	ActualTrack   *string `protobuf:"bytes,2,opt,name=actual_track,json=actualTrack" json:"actual_track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NyctStopTimeUpdate) Reset() {
	*x = NyctStopTimeUpdate{}
	mi := &file_internal_pb_gtfs_realtime_nyct_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NyctStopTimeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NyctStopTimeUpdate) ProtoMessage() {}

func (x *NyctStopTimeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_gtfs_realtime_nyct_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NyctStopTimeUpdate.ProtoReflect.Descriptor instead.
func (*NyctStopTimeUpdate) Descriptor() ([]byte, []int) {
	return file_internal_pb_gtfs_realtime_nyct_proto_rawDescGZIP(), []int{3}
}

func (x *NyctStopTimeUpdate) GetScheduledTrack() string {
	if x != nil && x.ScheduledTrack != nil {
		return *x.ScheduledTrack
	}
	return ""
}

func (x *NyctStopTimeUpdate) GetActualTrack() string {
	if x != nil && x.ActualTrack != nil {
		return *x.ActualTrack
	}
	return ""
}

var file_internal_pb_gtfs_realtime_nyct_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*FeedHeader)(nil),
		ExtensionType: (*NyctFeedHeader)(nil),
		Field:         1001,
		Name:          "pb.nyct_feed_header",
		Tag:           "bytes,1001,opt,name=nyct_feed_header",
		Filename:      "internal/pb/gtfs_realtime_nyct.proto",
	},
	{
		ExtendedType:  (*TripDescriptor)(nil),
		ExtensionType: (*NyctTripDescriptor)(nil),
		Field:         1001,
		Name:          "pb.nyct_trip_descriptor",
		Tag:           "bytes,1001,opt,name=nyct_trip_descriptor",
		Filename:      "internal/pb/gtfs_realtime_nyct.proto",
	},
	{
		ExtendedType:  (*TripUpdate_StopTimeUpdate)(nil),
		ExtensionType: (*NyctStopTimeUpdate)(nil),
		Field:         1001,
		Name:          "pb.nyct_stop_time_update",
		Tag:           "bytes,1001,opt,name=nyct_stop_time_update",
		Filename:      "internal/pb/gtfs_realtime_nyct.proto",
	},
}

// Extension fields to FeedHeader.
var (
	// optional pb.NyctFeedHeader nyct_feed_header = 1001;
	E_NyctFeedHeader = &file_internal_pb_gtfs_realtime_nyct_proto_extTypes[0]
)

// Extension fields to TripDescriptor.
var (
	// optional pb.NyctTripDescriptor nyct_trip_descriptor = 1001;
	E_NyctTripDescriptor = &file_internal_pb_gtfs_realtime_nyct_proto_extTypes[1]
)

// Extension fields to TripUpdate_StopTimeUpdate.
var (
	// optional pb.NyctStopTimeUpdate nyct_stop_time_update = 1001;
	E_NyctStopTimeUpdate = &file_internal_pb_gtfs_realtime_nyct_proto_extTypes[2]
)

var File_internal_pb_gtfs_realtime_nyct_proto protoreflect.FileDescriptor

const file_internal_pb_gtfs_realtime_nyct_proto_rawDesc = "" +
	"\n" +
	"$internal/pb/gtfs_realtime_nyct.proto\x12\x02pb\x1a\x1finternal/pb/gtfs_realtime.proto\"p\n" +
	"\x15TripReplacementPeriod\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12<\n" +
	"\x12replacement_period\x18\x02 \x01(\v2\r.pb.TimeRangeR\x11replacementPeriod\"\x93\x01\n" +
	"\x0eNyctFeedHeader\x12.\n" +
	"\x13nyct_subway_version\x18\x01 \x02(\tR\x11nyctSubwayVersion\x12Q\n" +
	"\x17trip_replacement_period\x18\x02 \x03(\v2\x19.pb.TripReplacementPeriodR\x15tripReplacementPeriod\"\xc7\x01\n" +
	"\x12NyctTripDescriptor\x12\x19\n" +
	"\btrain_id\x18\x01 \x01(\tR\atrainId\x12\x1f\n" +
	"\vis_assigned\x18\x02 \x01(\bR\n" +
	"isAssigned\x12>\n" +
	"\tdirection\x18\x03 \x01(\x0e2 .pb.NyctTripDescriptor.DirectionR\tdirection\"5\n" +
	"\tDirection\x12\t\n" +
	"\x05NORTH\x10\x01\x12\b\n" +
	"\x04EAST\x10\x02\x12\t\n" +
	"\x05SOUTH\x10\x03\x12\b\n" +
	"\x04WEST\x10\x04\"`\n" +
	"\x12NyctStopTimeUpdate\x12'\n" +
	"\x0fscheduled_track\x18\x01 \x01(\tR\x0escheduledTrack\x12!\n" +
	"\factual_track\x18\x02 \x01(\tR\vactualTrack:M\n" +
	"\x10nyct_feed_header\x12\x0e.pb.FeedHeader\x18\xe9\a \x01(\v2\x12.pb.NyctFeedHeaderR\x0enyctFeedHeader:]\n" +
	"\x14nyct_trip_descriptor\x12\x12.pb.TripDescriptor\x18\xe9\a \x01(\v2\x16.pb.NyctTripDescriptorR\x12nyctTripDescriptor:i\n" +
	"\x15nyct_stop_time_update\x12\x1d.pb.TripUpdate.StopTimeUpdate\x18\xe9\a \x01(\v2\x16.pb.NyctStopTimeUpdateR\x12nyctStopTimeUpdateB\x17Z\x15nyct-feed/internal/pb"

var (
	file_internal_pb_gtfs_realtime_nyct_proto_rawDescOnce sync.Once
	file_internal_pb_gtfs_realtime_nyct_proto_rawDescData []byte
)

func file_internal_pb_gtfs_realtime_nyct_proto_rawDescGZIP() []byte {
	file_internal_pb_gtfs_realtime_nyct_proto_rawDescOnce.Do(func() {
		file_internal_pb_gtfs_realtime_nyct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_gtfs_realtime_nyct_proto_rawDesc), len(file_internal_pb_gtfs_realtime_nyct_proto_rawDesc)))
	})
	return file_internal_pb_gtfs_realtime_nyct_proto_rawDescData
}

var file_internal_pb_gtfs_realtime_nyct_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_gtfs_realtime_nyct_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_pb_gtfs_realtime_nyct_proto_goTypes = []any{
	(NyctTripDescriptor_Direction)(0), // 0: pb.NyctTripDescriptor.Direction
	(*TripReplacementPeriod)(nil),     // 1: pb.TripReplacementPeriod
	(*NyctFeedHeader)(nil),            // 2: pb.NyctFeedHeader
	(*NyctTripDescriptor)(nil),        // 3: pb.NyctTripDescriptor
	(*NyctStopTimeUpdate)(nil),        // 4: pb.NyctStopTimeUpdate
	(*TimeRange)(nil),                 // 5: pb.TimeRange
	(*FeedHeader)(nil),                // 6: pb.FeedHeader
	(*TripDescriptor)(nil),            // 7: pb.TripDescriptor
	(*TripUpdate_StopTimeUpdate)(nil), // 8: pb.TripUpdate.StopTimeUpdate
}
var file_internal_pb_gtfs_realtime_nyct_proto_depIdxs = []int32{
	5, // 0: pb.TripReplacementPeriod.replacement_period:type_name -> pb.TimeRange
	1, // 1: pb.NyctFeedHeader.trip_replacement_period:type_name -> pb.TripReplacementPeriod
	0, // 2: pb.NyctTripDescriptor.direction:type_name -> pb.NyctTripDescriptor.Direction
	6, // 3: pb.nyct_feed_header:extendee -> pb.FeedHeader
	7, // 4: pb.nyct_trip_descriptor:extendee -> pb.TripDescriptor
	8, // 5: pb.nyct_stop_time_update:extendee -> pb.TripUpdate.StopTimeUpdate
	2, // 6: pb.nyct_feed_header:type_name -> pb.NyctFeedHeader
	3, // 7: pb.nyct_trip_descriptor:type_name -> pb.NyctTripDescriptor
	4, // 8: pb.nyct_stop_time_update:type_name -> pb.NyctStopTimeUpdate
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	6, // [6:9] is the sub-list for extension type_name
	3, // [3:6] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_pb_gtfs_realtime_nyct_proto_init() }
func file_internal_pb_gtfs_realtime_nyct_proto_init() {
	if File_internal_pb_gtfs_realtime_nyct_proto != nil {
		return
	}
	file_internal_pb_gtfs_realtime_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_gtfs_realtime_nyct_proto_rawDesc), len(file_internal_pb_gtfs_realtime_nyct_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_gtfs_realtime_nyct_proto_goTypes,
		DependencyIndexes: file_internal_pb_gtfs_realtime_nyct_proto_depIdxs,
		EnumInfos:         file_internal_pb_gtfs_realtime_nyct_proto_enumTypes,
		MessageInfos:      file_internal_pb_gtfs_realtime_nyct_proto_msgTypes,
		ExtensionInfos:    file_internal_pb_gtfs_realtime_nyct_proto_extTypes,
	}.Build()
	File_internal_pb_gtfs_realtime_nyct_proto = out.File
	file_internal_pb_gtfs_realtime_nyct_proto_goTypes = nil
	file_internal_pb_gtfs_realtime_nyct_proto_depIdxs = nil
}
