// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Calendar struct {
	ServiceID string `json:"service_id"`
	Monday    int64  `json:"monday"`
	Tuesday   int64  `json:"tuesday"`
	Wednesday int64  `json:"wednesday"`
	Thursday  int64  `json:"thursday"`
	Friday    int64  `json:"friday"`
	Saturday  int64  `json:"saturday"`
	Sunday    int64  `json:"sunday"`
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

type CalendarDate struct {
	ServiceID     string `json:"service_id"`
	Date          string `json:"date"`
	ExceptionType int64  `json:"exception_type"`
}

type Route struct {
	RouteID        string `json:"route_id"`
	AgencyID       string `json:"agency_id"`
	RouteShortName string `json:"route_short_name"`
	RouteLongName  string `json:"route_long_name"`
	RouteDesc      string `json:"route_desc"`
	RouteType      int64  `json:"route_type"`
	RouteUrl       string `json:"route_url"`
	RouteColor     string `json:"route_color"`
	RouteTextColor string `json:"route_text_color"`
	RouteSortOrder int64  `json:"route_sort_order"`
}

type Stop struct {
	StopID        string         `json:"stop_id"`
	StopName      string         `json:"stop_name"`
	StopLat       float64        `json:"stop_lat"`
	StopLon       float64        `json:"stop_lon"`
	LocationType  int64          `json:"location_type"`
	ParentStation sql.NullString `json:"parent_station"`
}

type StopTime struct {
	TripID        string `json:"trip_id"`
	StopID        string `json:"stop_id"`
	ArrivalTime   string `json:"arrival_time"`
	DepartureTime string `json:"departure_time"`
	StopSequence  int64  `json:"stop_sequence"`
}

type Trip struct {
	TripID       string `json:"trip_id"`
	RouteID      string `json:"route_id"`
	ServiceID    string `json:"service_id"`
	TripHeadsign string `json:"trip_headsign"`
	DirectionID  int64  `json:"direction_id"`
	ShapeID      string `json:"shape_id"`
}
