// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const deleteCalendarDates = `-- name: DeleteCalendarDates :exec
DELETE FROM calendar_dates
`

func (q *Queries) DeleteCalendarDates(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteCalendarDatesStmt, deleteCalendarDates)
	return err
}

const deleteCalendars = `-- name: DeleteCalendars :exec
DELETE FROM calendars
`

func (q *Queries) DeleteCalendars(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteCalendarsStmt, deleteCalendars)
	return err
}

const deleteRoutes = `-- name: DeleteRoutes :exec
DELETE FROM routes
`

func (q *Queries) DeleteRoutes(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteRoutesStmt, deleteRoutes)
	return err
}

const deleteStopTimes = `-- name: DeleteStopTimes :exec
DELETE FROM stop_times
`

func (q *Queries) DeleteStopTimes(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteStopTimesStmt, deleteStopTimes)
	return err
}

const deleteStops = `-- name: DeleteStops :exec
DELETE FROM stops
`

func (q *Queries) DeleteStops(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteStopsStmt, deleteStops)
	return err
}

const deleteTrips = `-- name: DeleteTrips :exec
DELETE FROM trips
`

func (q *Queries) DeleteTrips(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteTripsStmt, deleteTrips)
	return err
}

const insertCalendar = `-- name: InsertCalendar :exec
INSERT INTO calendars (service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCalendarParams struct {
	ServiceID string `json:"service_id"`
	Monday    int64  `json:"monday"`
	Tuesday   int64  `json:"tuesday"`
	Wednesday int64  `json:"wednesday"`
	Thursday  int64  `json:"thursday"`
	Friday    int64  `json:"friday"`
	Saturday  int64  `json:"saturday"`
	Sunday    int64  `json:"sunday"`
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

func (q *Queries) InsertCalendar(ctx context.Context, arg InsertCalendarParams) error {
	_, err := q.exec(ctx, q.insertCalendarStmt, insertCalendar,
		arg.ServiceID,
		arg.Monday,
		arg.Tuesday,
		arg.Wednesday,
		arg.Thursday,
		arg.Friday,
		arg.Saturday,
		arg.Sunday,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const insertCalendarDate = `-- name: InsertCalendarDate :exec
INSERT INTO calendar_dates (service_id, date, exception_type)
VALUES (?, ?, ?)
`

type InsertCalendarDateParams struct {
	ServiceID     string `json:"service_id"`
	Date          string `json:"date"`
	ExceptionType int64  `json:"exception_type"`
}

func (q *Queries) InsertCalendarDate(ctx context.Context, arg InsertCalendarDateParams) error {
	_, err := q.exec(ctx, q.insertCalendarDateStmt, insertCalendarDate, arg.ServiceID, arg.Date, arg.ExceptionType)
	return err
}

const insertRoute = `-- name: InsertRoute :exec
INSERT INTO routes (route_id, agency_id, route_short_name, route_long_name, route_desc, route_type, route_url, route_color, route_text_color, route_sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRouteParams struct {
	RouteID        string `json:"route_id"`
	AgencyID       string `json:"agency_id"`
	RouteShortName string `json:"route_short_name"`
	RouteLongName  string `json:"route_long_name"`
	RouteDesc      string `json:"route_desc"`
	RouteType      int64  `json:"route_type"`
	RouteUrl       string `json:"route_url"`
	RouteColor     string `json:"route_color"`
	RouteTextColor string `json:"route_text_color"`
	RouteSortOrder int64  `json:"route_sort_order"`
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) error {
	_, err := q.exec(ctx, q.insertRouteStmt, insertRoute,
		arg.RouteID,
		arg.AgencyID,
		arg.RouteShortName,
		arg.RouteLongName,
		arg.RouteDesc,
		arg.RouteType,
		arg.RouteUrl,
		arg.RouteColor,
		arg.RouteTextColor,
		arg.RouteSortOrder,
	)
	return err
}

const insertStop = `-- name: InsertStop :exec
INSERT INTO stops (stop_id, stop_name, stop_lat, stop_lon, location_type, parent_station)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertStopParams struct {
	StopID        string         `json:"stop_id"`
	StopName      string         `json:"stop_name"`
	StopLat       float64        `json:"stop_lat"`
	StopLon       float64        `json:"stop_lon"`
	LocationType  int64          `json:"location_type"`
	ParentStation sql.NullString `json:"parent_station"`
}

func (q *Queries) InsertStop(ctx context.Context, arg InsertStopParams) error {
	_, err := q.exec(ctx, q.insertStopStmt, insertStop,
		arg.StopID,
		arg.StopName,
		arg.StopLat,
		arg.StopLon,
		arg.LocationType,
		arg.ParentStation,
	)
	return err
}

const insertStopTime = `-- name: InsertStopTime :exec
INSERT INTO stop_times (trip_id, stop_id, arrival_time, departure_time, stop_sequence)
VALUES (?, ?, ?, ?, ?)
`

type InsertStopTimeParams struct {
	TripID        string `json:"trip_id"`
	StopID        string `json:"stop_id"`
	ArrivalTime   string `json:"arrival_time"`
	DepartureTime string `json:"departure_time"`
	StopSequence  int64  `json:"stop_sequence"`
}

func (q *Queries) InsertStopTime(ctx context.Context, arg InsertStopTimeParams) error {
	_, err := q.exec(ctx, q.insertStopTimeStmt, insertStopTime,
		arg.TripID,
		arg.StopID,
		arg.ArrivalTime,
		arg.DepartureTime,
		arg.StopSequence,
	)
	return err
}

const insertTrip = `-- name: InsertTrip :exec
INSERT INTO trips (trip_id, route_id, service_id, trip_headsign, direction_id, shape_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTripParams struct {
	TripID       string `json:"trip_id"`
	RouteID      string `json:"route_id"`
	ServiceID    string `json:"service_id"`
	TripHeadsign string `json:"trip_headsign"`
	DirectionID  int64  `json:"direction_id"`
	ShapeID      string `json:"shape_id"`
}

func (q *Queries) InsertTrip(ctx context.Context, arg InsertTripParams) error {
	_, err := q.exec(ctx, q.insertTripStmt, insertTrip,
		arg.TripID,
		arg.RouteID,
		arg.ServiceID,
		arg.TripHeadsign,
		arg.DirectionID,
		arg.ShapeID,
	)
	return err
}
